use ArtiFindDB
go
INSERT INTO Interests (InterestName) VALUES('Activism')
INSERT INTO Interests (InterestName) VALUES('Addiction')
INSERT INTO Interests (InterestName) VALUES('Agriculture')
 INSERT INTO Interests (InterestName) VALUES('AI')
INSERT INTO Interests (InterestName) VALUES('Algorithm')
INSERT INTO Interests (InterestName) VALUES('Aliens')
INSERT INTO Interests (InterestName) VALUES('Ancient world')
 INSERT INTO Interests (InterestName) VALUES('Animals')
INSERT INTO Interests (InterestName) VALUES('Animation')
INSERT INTO Interests (InterestName) VALUES('Antarctica')
INSERT INTO Interests (InterestName) VALUES('Archaeology')
INSERT INTO Interests (InterestName) VALUES('Architecture')
INSERT INTO Interests (InterestName) VALUES('Art')
INSERT INTO Interests (InterestName) VALUES('Asteroid')
INSERT INTO Interests (InterestName) VALUES('Astrobiology')
 INSERT INTO Interests (InterestName) VALUES('Astronomy')
INSERT INTO Interests (InterestName) VALUES('Atheism')
INSERT INTO Interests (InterestName) VALUES('Augmented reality')
INSERT INTO Interests (InterestName) VALUES('Bacteria')
INSERT INTO Interests (InterestName) VALUES('Big Bang')
 INSERT INTO Interests (InterestName) VALUES('Biology')
INSERT INTO Interests (InterestName) VALUES('Biotech')
 INSERT INTO Interests (InterestName) VALUES('Books')
 INSERT INTO Interests (InterestName) VALUES('Botany')
 INSERT INTO Interests (InterestName) VALUES('Brain')
INSERT INTO Interests (InterestName) VALUES('Buddhism')
 INSERT INTO Interests (InterestName) VALUES('Business')
 INSERT INTO Interests (InterestName) VALUES('Cancer')
 INSERT INTO Interests (InterestName) VALUES('Capitalism')
 INSERT INTO Interests (InterestName) VALUES('Chemistry')
INSERT INTO Interests (InterestName) VALUES('Christianity')
 INSERT INTO Interests (InterestName) VALUES('Climate change')
INSERT INTO Interests (InterestName) VALUES('Code')
INSERT INTO Interests (InterestName) VALUES('Cognitive science')
INSERT INTO Interests (InterestName) VALUES('Communication')
INSERT INTO Interests (InterestName) VALUES('Community')
 INSERT INTO Interests (InterestName) VALUES('Computers')
INSERT INTO Interests (InterestName) VALUES('Coral reefs')
INSERT INTO Interests (InterestName) VALUES('Coronavirus')
INSERT INTO Interests (InterestName) VALUES('Creativity')
INSERT INTO Interests (InterestName) VALUES('Crime')
INSERT INTO Interests (InterestName) VALUES('CRISPR')
 INSERT INTO Interests (InterestName) VALUES('Cryptocurrency')
 INSERT INTO Interests (InterestName) VALUES('Culture')
 INSERT INTO Interests (InterestName) VALUES('Cyber security')
 INSERT INTO Interests (InterestName) VALUES('Dance')
INSERT INTO Interests (InterestName) VALUES('Dark matter')
INSERT INTO Interests (InterestName) VALUES('Data')
INSERT INTO Interests (InterestName) VALUES('Decision-making')
 INSERT INTO Interests (InterestName) VALUES('Democracy')
INSERT INTO Interests (InterestName) VALUES('Depression')
INSERT INTO Interests (InterestName) VALUES('Design')
 INSERT INTO Interests (InterestName) VALUES('Dinosaurs')
INSERT INTO Interests (InterestName) VALUES('Disability')
INSERT INTO Interests (InterestName) VALUES('Discovery')
 INSERT INTO Interests (InterestName) VALUES('Disease')
INSERT INTO Interests (InterestName) VALUES('Diversity')
 INSERT INTO Interests (InterestName) VALUES('DNA')
 INSERT INTO Interests (InterestName) VALUES('Driverless cars')
INSERT INTO Interests (InterestName) VALUES('Drones')
INSERT INTO Interests (InterestName) VALUES('Drugs')
INSERT INTO Interests (InterestName) VALUES('Ecology')
 INSERT INTO Interests (InterestName) VALUES('Economics')
 INSERT INTO Interests (InterestName) VALUES('Education')
 INSERT INTO Interests (InterestName) VALUES('Electricity')
 INSERT INTO Interests (InterestName) VALUES('Emotions')
INSERT INTO Interests (InterestName) VALUES('Encryption')
 INSERT INTO Interests (InterestName) VALUES('Energy')
 INSERT INTO Interests (InterestName) VALUES('Engineering')
INSERT INTO Interests (InterestName) VALUES('Entertainment')
INSERT INTO Interests (InterestName) VALUES('Entrepreneur')
 INSERT INTO Interests (InterestName) VALUES('Environment')
INSERT INTO Interests (InterestName) VALUES('Equality')
INSERT INTO Interests (InterestName) VALUES('Ethics')
INSERT INTO Interests (InterestName) VALUES('Evolution')
INSERT INTO Interests (InterestName) VALUES('Exercise')
INSERT INTO Interests (InterestName) VALUES('Family')
INSERT INTO Interests (InterestName) VALUES('Farming')
 INSERT INTO Interests (InterestName) VALUES('Feminism')
INSERT INTO Interests (InterestName) VALUES('Film')
 INSERT INTO Interests (InterestName) VALUES('Finance')
INSERT INTO Interests (InterestName) VALUES('Food')
INSERT INTO Interests (InterestName) VALUES('Fossil fuels')
 INSERT INTO Interests (InterestName) VALUES('Gaming')
 INSERT INTO Interests (InterestName) VALUES('Genetics')
 INSERT INTO Interests (InterestName) VALUES('Geology')
INSERT INTO Interests (InterestName) VALUES('Glaciers')
INSERT INTO Interests (InterestName) VALUES('Global issues')
 INSERT INTO Interests (InterestName) VALUES('Government')
INSERT INTO Interests (InterestName) VALUES('Grammar')
INSERT INTO Interests (InterestName) VALUES('Graphic design')
 INSERT INTO Interests (InterestName) VALUES('Health')
INSERT INTO Interests (InterestName) VALUES('Health care')
INSERT INTO Interests (InterestName) VALUES('Hearing')
 INSERT INTO Interests (InterestName) VALUES('Heart')
INSERT INTO Interests (InterestName) VALUES('Hinduism')
 INSERT INTO Interests (InterestName) VALUES('History')
 INSERT INTO Interests (InterestName) VALUES('Human body')
INSERT INTO Interests (InterestName) VALUES('Human rights')
INSERT INTO Interests (InterestName) VALUES('Humanities')
INSERT INTO Interests (InterestName) VALUES('Humanity')
INSERT INTO Interests (InterestName) VALUES('Illness')
INSERT INTO Interests (InterestName) VALUES('Industrial design')
INSERT INTO Interests (InterestName) VALUES('Innovation')
INSERT INTO Interests (InterestName) VALUES('International development')
INSERT INTO Interests (InterestName) VALUES('International relations')
 INSERT INTO Interests (InterestName) VALUES('Internet')
INSERT INTO Interests (InterestName) VALUES('Invention')
INSERT INTO Interests (InterestName) VALUES('Investing')
INSERT INTO Interests (InterestName) VALUES('Islam')
INSERT INTO Interests (InterestName) VALUES('Journalism')
INSERT INTO Interests (InterestName) VALUES('Judaism')
 INSERT INTO Interests (InterestName) VALUES('Justice system')
INSERT INTO Interests (InterestName) VALUES('Kids')
INSERT INTO Interests (InterestName) VALUES('Language')
 INSERT INTO Interests (InterestName) VALUES('Law')
INSERT INTO Interests (InterestName) VALUES('Leadership')
 INSERT INTO Interests (InterestName) VALUES('LGBT')
INSERT INTO Interests (InterestName) VALUES('Life')
 INSERT INTO Interests (InterestName) VALUES('Literature')
INSERT INTO Interests (InterestName) VALUES('Love')
 INSERT INTO Interests (InterestName) VALUES('Machine learning')
INSERT INTO Interests (InterestName) VALUES('Magic')
INSERT INTO Interests (InterestName) VALUES('Manufacturing')
INSERT INTO Interests (InterestName) VALUES('Marine biology')
INSERT INTO Interests (InterestName) VALUES('Marketing')
INSERT INTO Interests (InterestName) VALUES('Mars')
 INSERT INTO Interests (InterestName) VALUES('Math')
INSERT INTO Interests (InterestName) VALUES('Media')
INSERT INTO Interests (InterestName) VALUES('Medical research')
INSERT INTO Interests (InterestName) VALUES('Medicine')
INSERT INTO Interests (InterestName) VALUES('Meditation')
 INSERT INTO Interests (InterestName) VALUES('Memory')
INSERT INTO Interests (InterestName) VALUES('Mental health')
INSERT INTO Interests (InterestName) VALUES('Microbes')
 INSERT INTO Interests (InterestName) VALUES('Microbiology')
INSERT INTO Interests (InterestName) VALUES('Middle East')
INSERT INTO Interests (InterestName) VALUES('Military')
INSERT INTO Interests (InterestName) VALUES('Money')
INSERT INTO Interests (InterestName) VALUES('Moon')
INSERT INTO Interests (InterestName) VALUES('Motivation')
 INSERT INTO Interests (InterestName) VALUES('Music')
 INSERT INTO Interests (InterestName) VALUES('Nanotechnology')
INSERT INTO Interests (InterestName) VALUES('NASA')
 INSERT INTO Interests (InterestName) VALUES('Natural disaster')
INSERT INTO Interests (InterestName) VALUES('Natural resources')
 INSERT INTO Interests (InterestName) VALUES('Nature')
INSERT INTO Interests (InterestName) VALUES('Neurology')
 INSERT INTO Interests (InterestName) VALUES('Neuroscience')
INSERT INTO Interests (InterestName) VALUES('Nuclear energy')
 INSERT INTO Interests (InterestName) VALUES('Ocean')
INSERT INTO Interests (InterestName) VALUES('Online privacy')
INSERT INTO Interests (InterestName) VALUES('Pain')
 INSERT INTO Interests (InterestName) VALUES('Painting')
INSERT INTO Interests (InterestName) VALUES('Pandemic')
INSERT INTO Interests (InterestName) VALUES('Performance')
INSERT INTO Interests (InterestName) VALUES('Personal growth')
INSERT INTO Interests (InterestName) VALUES('Personality')
INSERT INTO Interests (InterestName) VALUES('Philanthropy')
 INSERT INTO Interests (InterestName) VALUES('Philosophy')
INSERT INTO Interests (InterestName) VALUES('Photography')
 INSERT INTO Interests (InterestName) VALUES('Physics')
 INSERT INTO Interests (InterestName) VALUES('Planets')
INSERT INTO Interests (InterestName) VALUES('Plants')
INSERT INTO Interests (InterestName) VALUES('Plastic')
INSERT INTO Interests (InterestName) VALUES('Poetry')
INSERT INTO Interests (InterestName) VALUES('Policy')
 INSERT INTO Interests (InterestName) VALUES('Politics')
INSERT INTO Interests (InterestName) VALUES('Pollution')
INSERT INTO Interests (InterestName) VALUES('Poverty')
INSERT INTO Interests (InterestName) VALUES('Pregnancy')
INSERT INTO Interests (InterestName) VALUES('Prison')
INSERT INTO Interests (InterestName) VALUES('Protest')
INSERT INTO Interests (InterestName) VALUES('Psychology')
INSERT INTO Interests (InterestName) VALUES('Public health')
 INSERT INTO Interests (InterestName) VALUES('Quantum')
INSERT INTO Interests (InterestName) VALUES('Race')
INSERT INTO Interests (InterestName) VALUES('Relationships')
 INSERT INTO Interests (InterestName) VALUES('Religion')
 INSERT INTO Interests (InterestName) VALUES('Renewable energy')
INSERT INTO Interests (InterestName) VALUES('Resources')
INSERT INTO Interests (InterestName) VALUES('Rivers')
INSERT INTO Interests (InterestName) VALUES('Robots')
 INSERT INTO Interests (InterestName) VALUES('Rocket science')
 INSERT INTO Interests (InterestName) VALUES('Science')
INSERT INTO Interests (InterestName) VALUES('Science fiction')
INSERT INTO Interests (InterestName) VALUES('Sexual violence')
INSERT INTO Interests (InterestName) VALUES('Shopping')
INSERT INTO Interests (InterestName) VALUES('Slavery')
INSERT INTO Interests (InterestName) VALUES('Sleep')
INSERT INTO Interests (InterestName) VALUES('Smell')
INSERT INTO Interests (InterestName) VALUES('Social media')
INSERT INTO Interests (InterestName) VALUES('Society')
 INSERT INTO Interests (InterestName) VALUES('Sociology')
INSERT INTO Interests (InterestName) VALUES('Software')
INSERT INTO Interests (InterestName) VALUES('Solar energy')
INSERT INTO Interests (InterestName) VALUES('Solar system')
INSERT INTO Interests (InterestName) VALUES('Sound')
 INSERT INTO Interests (InterestName) VALUES('Space')
 INSERT INTO Interests (InterestName) VALUES('Sports')
INSERT INTO Interests (InterestName) VALUES('Statistics')
INSERT INTO Interests (InterestName) VALUES('Street art')
 INSERT INTO Interests (InterestName) VALUES('String theory')
INSERT INTO Interests (InterestName) VALUES('Success')
INSERT INTO Interests (InterestName) VALUES('Suicide')
INSERT INTO Interests (InterestName) VALUES('Sun')
INSERT INTO Interests (InterestName) VALUES('Surgery')
INSERT INTO Interests (InterestName) VALUES('Surveillance')
INSERT INTO Interests (InterestName) VALUES('Sustainability')
INSERT INTO Interests (InterestName) VALUES('Synthetic biology')
INSERT INTO Interests (InterestName) VALUES('Teaching')
 INSERT INTO Interests (InterestName) VALUES('Technology')
INSERT INTO Interests (InterestName) VALUES('Telescopes')
INSERT INTO Interests (InterestName) VALUES('Television')
INSERT INTO Interests (InterestName) VALUES('Terrorism')
INSERT INTO Interests (InterestName) VALUES('Theater')
INSERT INTO Interests (InterestName) VALUES('Time')
INSERT INTO Interests (InterestName) VALUES('Toys')
INSERT INTO Interests (InterestName) VALUES('Transportation')
INSERT INTO Interests (InterestName) VALUES('Travel')
INSERT INTO Interests (InterestName) VALUES('Trees')
 INSERT INTO Interests (InterestName) VALUES('Universe')
INSERT INTO Interests (InterestName) VALUES('Urban planning')
INSERT INTO Interests (InterestName) VALUES('Vaccines')
INSERT INTO Interests (InterestName) VALUES('Violence')
 INSERT INTO Interests (InterestName) VALUES('Virtual reality')
 INSERT INTO Interests (InterestName) VALUES('Virus')
INSERT INTO Interests (InterestName) VALUES('Visualizations')
INSERT INTO Interests (InterestName) VALUES('Vulnerability')
INSERT INTO Interests (InterestName) VALUES('War')
INSERT INTO Interests (InterestName) VALUES('Water')
INSERT INTO Interests (InterestName) VALUES('Weather')
INSERT INTO Interests (InterestName) VALUES('Wind energy')
INSERT INTO Interests (InterestName) VALUES('Women')
INSERT INTO Interests (InterestName) VALUES('Women in business')
INSERT INTO Interests (InterestName) VALUES('Work')
INSERT INTO Interests (InterestName) VALUES('Writing')
insert into users (FirstName,
    LastName ,
    UserName ,
    BirthDay ,
    Email ,
    Pswd ,
    IsManger ) VALUES
    ('Amit', 'Yogev', 'Amit2609','26-sep-2004', 'amity2609@gmail.com','1234', 1)